#encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# Environment variables (ENV['...']) can be set in the file config/application.yml.
# See http://railsapps.github.io/rails-environment-variables.html
puts 'ROLES'
YAML.load(ENV['ROLES']).each do |role|
  Role.find_or_create_by_name({ :name => role }, :without_protection => true)
  puts 'role: ' << role
end
puts 'DEFAULT USERS'
user = User.find_or_create_by_email :name => ENV['ADMIN_NAME'].dup, :email => ENV['ADMIN_EMAIL'].dup, :password => ENV['ADMIN_PASSWORD'].dup, :password_confirmation => ENV['ADMIN_PASSWORD'].dup
puts 'user: ' << user.name
user.confirm!
user.add_role :admin




Menu.create!(name: "100% Whole Wheat Bread #1")
Menu.create!(name: "( From Bread Mix ) Homemade White Bread")
Menu.create!(name: "\"Kentucky Friend Chicken\" Coleslaw")
Menu.create!(name: "A 15-Minute Stir Fry")
Menu.create!(name: "7-Up Cake #2")
Menu.create!(name: "Aceitunas Alinadas (Olives in Oil)")
Menu.create!(name: "Al Rice Blacken Blend")
Menu.create!(name: "All Season Apple Pie")
Menu.create!(name: "All-American Dessert")
Menu.create!(name: "Altdeutxche Brotchen (Old German Muffins)")
Menu.create!(name: "Almond Crumb Cake Muffins")
Menu.create!(name: "Almond Meringue Cake with Strawberry and Vanilla Ice Crm Pt2")
Menu.create!(name: "Amy Scherber's Rosemary Fougasse")
Menu.create!(name: "Amish Cake")
Menu.create!(name: "Angel Food Cake")
Menu.create!(name: "Apple and Almond Macaroon Pudding")
Menu.create!(name: "Aniseed Cookies")
Menu.create!(name: "Apple Blueberry Pie")
Menu.create!(name: "Apple Oat Muffins (Ovo Lacto)")
Menu.create!(name: "Apple Cake with Icing")
Menu.create!(name: "Apple Oatmeal Raisin")
Menu.create!(name: "Apple-Ginger Upside-Down Cake")
Menu.create!(name: "Apple-Walnut Muffins")
Menu.create!(name: "Apples in Red Wine")
Menu.create!(name: "Apricot-Fig Bread")
Menu.create!(name: "Apricot Balls (Marillenknoedel)")
Menu.create!(name: "Apricot Cupcakes")
Menu.create!(name: "Artichoke Chili Stuffed Potato (Oaks)")
Menu.create!(name: "Artichoke and Cracked Wheat Bread Abm")
Menu.create!(name: "Artichoke Bake")
Menu.create!(name: "Auntie Ruth's Wash Day Beans")
Menu.create!(name: "Aussie Lentil Burgers")
Menu.create!(name: "Australian Christmas Cake")
Menu.create!(name: "Bacon Cheese Loaf")
Menu.create!(name: "Avocado and Crab Meat Salad")
Menu.create!(name: "Bachelor Buttons")
Menu.create!(name: "Badhapu Malu (Fried Fish)")
Menu.create!(name: "Baked Aubegines / Eggplants with Cheese (Greek)")
Menu.create!(name: "Baked Barley")
Menu.create!(name: "Baked Flounder with Scallop Stuffing")
Menu.create!(name: "Baked Macaroni and Tomatoes")
Menu.create!(name: "Baked Chicken Breasts with Cheese")
Menu.create!(name: "Baked Pear with Caramel Sauce")
Menu.create!(name: "Baked Potato Wedges")
Menu.create!(name: "Baked Stuffed Eggs")
Menu.create!(name: "Baklava 2")
Menu.create!(name: "Banana Butter")
Menu.create!(name: "Balsamico Chicken with Olives")
Menu.create!(name: "Barb's Best Crisp")
Menu.create!(name: "Banana-Brownie Cake")
Menu.create!(name: "Bananas Foster #2")
Menu.create!(name: "Barbecued Spareribs (Or Chicken)")
Menu.create!(name: "Barbequed (In a Skillet) Franks")
Menu.create!(name: "Barley and Bean with Fresh Mint (Vegan)")
Menu.create!(name: "Basic Vinaigrette (Cooks Garden)")
Menu.create!(name: "Basic Whole Wheat")
Menu.create!(name: "Basic Leftover Casserole")
Menu.create!(name: "Bay Bugs Pan Seared on Noodles with Chilli Oils")
Menu.create!(name: "Basting Sauce for Barbecue")
Menu.create!(name: "Batter To Use for Deep Frying Foods")
Menu.create!(name: "Beef and Noodle Soup \"A la Vietnamese\"")
Menu.create!(name: "Beef and Potato Casserole")
Menu.create!(name: "Beef and Mushroom Roll")
Menu.create!(name: "Beef-Noodle Stove-Top Casserole")
Menu.create!(name: "Beef Stock 101")
Menu.create!(name: "Beer Biscuits #1")
Menu.create!(name: "Beet Soup/vegan")
Menu.create!(name: "Berliner Krantz")
Menu.create!(name: "Benihana Ginger Salad Dressing #2")
Menu.create!(name: "Beverage Base Pwdr")
Menu.create!(name: "Biscotti #04")
Menu.create!(name: "Biscotti Toscani")
Menu.create!(name: "Bl&t Bisque")
Menu.create!(name: "Black Bean Dip 2")
Menu.create!(name: "Black and White Bean Salad")
Menu.create!(name: "Blackened Fish Seasoning")
Menu.create!(name: "Blizzard")
Menu.create!(name: "Block Party Beans")
Menu.create!(name: "Blueberry Pie (Blueberrie")
Menu.create!(name: "Blue Cheese, Hazelnut and Herb Terrine")
Menu.create!(name: "Blueberry Couscous Cake")
Menu.create!(name: "Bologna Strata")
Menu.create!(name: "Boerenkass Soup (Dutch Cheese Soup)")
Menu.create!(name: "Bolillos (Mexican Rolls)")
Menu.create!(name: "Bran-Crammed Swiss Chard Rolls")
Menu.create!(name: "Braised Chicken with Bacon (Clay Pot)")
Menu.create!(name: "Braised Pheasant")
Menu.create!(name: "Bread Pudding W/whiskey Sauce")
Menu.create!(name: "Bread Machine Holiday Challah")
Menu.create!(name: "Breaded Veal Cutlets")
Menu.create!(name: "Broccoli Cheese Square")
Menu.create!(name: "Brined Dills")
Menu.create!(name: "Brigitte's German Cabbage Casserole")
Menu.create!(name: "Broiled Grapefruit")
Menu.create!(name: "Brownies")
Menu.create!(name: "Brown Rice Information")
Menu.create!(name: "Brunswick Stew Using Hogs Heads")
Menu.create!(name: "Buffalo Wings #2")
Menu.create!(name: "Brussel Sprouts Pie")
Menu.create!(name: "Butter Butter")
Menu.create!(name: "Buttered Saffron Rice")
Menu.create!(name: "Burgundy Style Beef")
Menu.create!(name: "Byron's Famous Killer Cheese Dip")
Menu.create!(name: "Cabbage Beef Soup Corrected")
Menu.create!(name: "Caesar Artichoke Swirls")
Menu.create!(name: "Camp Biscuits")
Menu.create!(name: "Canapé Butters")
Menu.create!(name: "Candied Red Chiles")
Menu.create!(name: "Capital Chicken Skillet")
Menu.create!(name: "Caramel Pie")
Menu.create!(name: "Caramel Marshmallow Bars")
Menu.create!(name: "Carma's \"He Didn't Know It Wasn't Meat\" Meatballs")
Menu.create!(name: "Carol's Favorite Vegetarian Chili")
Menu.create!(name: "Carl's Sourdough Bread")
Menu.create!(name: "Carrot Soup #1")
Menu.create!(name: "Carrot Poduthuval (Dry Carrot Curry)")
Menu.create!(name: "Casserole Del Italiano")
Menu.create!(name: "Cauliflower-Carrot Soup")
Menu.create!(name: "Cauliflower Microwave")
Menu.create!(name: "Cauliflower W/lime & Hot Pepper Vinaigre")
Menu.create!(name: "Cheddar Macaroni Salad")
Menu.create!(name: "Cheese Ball with Marinated Dried Tomatoes")
Menu.create!(name: "Cheese and Corn Strata")
Menu.create!(name: "Cheeseburger Baked Potatoes")
Menu.create!(name: "Cheese Souffle #1")
Menu.create!(name: "Cheese Tortellini with Red Pepper Dressing")
Menu.create!(name: "Cherry Cobbler Bars")
Menu.create!(name: "Cherried Sweet Potato Scallop")
Menu.create!(name: "Cherry Freezer Jam")
Menu.create!(name: "Chick Peas with Garlic and Green Chillies")
Menu.create!(name: "Chicken a la King (Usda)")
Menu.create!(name: "Chestnut-And-Lentil Soup")
Menu.create!(name: "Chicken Breasts Stuffed W/mozzarella")
Menu.create!(name: "Chicken and Shrimp")
Menu.create!(name: "Chicken Black Bean Paella")
Menu.create!(name: "Chicken Giblet Vegetable Soup")
Menu.create!(name: "Chicken Chiles Rellenos (Zarela Martinez)")
Menu.create!(name: "Chicken Escarole Soup")
Menu.create!(name: "Chicken Maderia with Portobello")
Menu.create!(name: "Chicken Rice Casserole")
Menu.create!(name: "Chicken Mallorca")
Menu.create!(name: "Chicken Stir-Fry Italian")
Menu.create!(name: "Chicken Waikiki Beach")
Menu.create!(name: "Chicken Tequila")
Menu.create!(name: "Chicken with Mushroom Gravy")
Menu.create!(name: "Chicken with Garlic and Parsley")
Menu.create!(name: "Chicken with Leeks and Apples")
Menu.create!(name: "Chili Sauce (Tomato)")
Menu.create!(name: "Chili Poblano Pie")
Menu.create!(name: "Chili Topping for Navajo Tacos")
Menu.create!(name: "Chilled Fillet of Beef with Sour Cream")
Menu.create!(name: "Chilled Red Pepper Soup")
Menu.create!(name: "Chiliburger")
Menu.create!(name: "Chipoltes En Adobo")
Menu.create!(name: "Chocolate Almond Coffee")
Menu.create!(name: "Chinese Vegetables and Tofu")
Menu.create!(name: "Chocolate Chip Brownies")
Menu.create!(name: "Chocolate Chip Sensation")
Menu.create!(name: "Chocolate Cashew Spread")
Menu.create!(name: "Chocolate Dream Bars")
Menu.create!(name: "Chocolate Covered Chocolate Cheesecake")
Menu.create!(name: "Chocolate Crunch Bars")
Menu.create!(name: "Chocolate or Cocoa Waffles")
Menu.create!(name: "Chocolate Orange Ribbon Cake")
Menu.create!(name: "Chocolate Lovers Mousse for Two")
Menu.create!(name: "Chocolate Swirl Cheesecake")
Menu.create!(name: "Chocolate Zucchini Brownies")
Menu.create!(name: "Chocolate Walnut Squares")
Menu.create!(name: "Chocolate-Date Log")
Menu.create!(name: "Christmas Stollen (Quick-Bread Variety)")
Menu.create!(name: "Chocolate-Coconut-Cherry Fudge")
Menu.create!(name: "Chutney Pecans")
Menu.create!(name: "Cider Fruit Punch a la Normande")
Menu.create!(name: "Chuck Steak with Deviled Sauce")
Menu.create!(name: "Classic Macaroni and Cheese")
Menu.create!(name: "Cinnamon-Raisin Bread")
Menu.create!(name: "Cinnamon Sugar Crusted Sweet Bread")
Menu.create!(name: "Cloud Covering for Grapes")
Menu.create!(name: "Classic Spam Potato Salad")
Menu.create!(name: "Cocoa Pecan Torte")
Menu.create!(name: "Coffee-Poblano Sauce")
Menu.create!(name: "Coffee Liquor Dipper Wings")
Menu.create!(name: "Coconut Pound Cake - Ella Merrill")
Menu.create!(name: "Cold Tomato Catsup")
Menu.create!(name: "CONFIT OF EXOTIC MUSHROOMS WITH FRESH ANGEL HAIR PASTA")
Menu.create!(name: "Coleslaw (Carter Family Favorites)")
Menu.create!(name: "Cookie Crumb Crust with Hazelnuts")
Menu.create!(name: "Cookie Tulips")
Menu.create!(name: "Copper Pennies")
Menu.create!(name: "Corn on the Cob (Frozen)")
Menu.create!(name: "Corn Chowder with Fresh Herbs and Smoked Ham")
Menu.create!(name: "Cornbread Salad (Tennessee Style)")
Menu.create!(name: "Country Style Pork Chops")
Menu.create!(name: "Cornmeal Honey Bread")
Menu.create!(name: "Cottage Cheese Cookies")
Menu.create!(name: "Crab Gumbo")
Menu.create!(name: "Crabmeat Au Gratin, Ii")
Menu.create!(name: "Couscous with Mushrooms")
Menu.create!(name: "Cranberries and Poultry")
Menu.create!(name: "Cranberry Catsup")
Menu.create!(name: "Cranberry Clafouti Cupsmartha Stewart")
Menu.create!(name: "Crawfish-Stuffed Beef Fillet")
Menu.create!(name: "Crazy Quilt Salad")
Menu.create!(name: "Cranberry Pecan Bars")
Menu.create!(name: "Cream of Pecan Soup")
Menu.create!(name: "Cream of Tomato Soup #3")
Menu.create!(name: "Cream of Veggie Soup")
Menu.create!(name: "Creamy Artichoke Hazelnut Soup")
Menu.create!(name: "Creamy Baked Chicken Breasts")
Menu.create!(name: "Creamy Caesar Dressing")
Menu.create!(name: "Creme Anglaise")
Menu.create!(name: "Crisco's Super-Crisp Country Fried Chicken")
Menu.create!(name: "Creamy Strawberry Parfaits")
Menu.create!(name: "Crock Pot Chili #2")
Menu.create!(name: "Crockpot Bake Beans")
Menu.create!(name: "Crock Pot Lemon Chicken")
Menu.create!(name: "Crockpot Pork Roast")
Menu.create!(name: "Crumb Topping - Martha Stewart Living")
Menu.create!(name: "Crunchy Bean Sprouts with Beef")
Menu.create!(name: "Curried Almond Cauliflower")
Menu.create!(name: "Crusty Pound Cake")
Menu.create!(name: "Cucumber, Tomato, Scallion, and Yogurt Relish")
Menu.create!(name: "Curried Fruit on Rice")
Menu.create!(name: "Curry Vinaigrette")
Menu.create!(name: "Curtis Aikens' Vegetarian Dressing")
Menu.create!(name: "Danablu Soup")
Menu.create!(name: "Date Syrup")
Menu.create!(name: "Dak's Walnut Blue Wheat Bread (Bread Machine)")
Menu.create!(name: "Dave's Bread")
Menu.create!(name: "Dehydrator Barbecue Sauce")
Menu.create!(name: "Death Wish Hot Sauce")
Menu.create!(name: "Diabetic Washington's Cherry Pie")
Menu.create!(name: "Dessert Puffs Using Basic Pie Crust Mix")
Menu.create!(name: "Devil's Food Cake (Mix)")
Menu.create!(name: "Dijon Bourbon Marinade")
Menu.create!(name: "Dietetic Peanuts")
Menu.create!(name: "Dilly Potato Salad")
Menu.create!(name: "Double Apple Salad")
Menu.create!(name: "Don K and Dolores Reed's Baked Ziti")
Menu.create!(name: "Double Chocolate Cookie Bars")
Menu.create!(name: "Dried Persimmons")
Menu.create!(name: "Dressed Cabbage")
Menu.create!(name: "Dryer Lint \"Paper Mache\"")
Menu.create!(name: "Eastern European Vegetable Dumplings")
Menu.create!(name: "Easy Applesauce Cake")
Menu.create!(name: "Dutch Oven Biscuits")
Menu.create!(name: "Easy Sweet and Sour Pork")
Menu.create!(name: "Easy Food Processor Banana Bread")
Menu.create!(name: "Easy Italian Chicken Breasts")
Menu.create!(name: "Easy White Chocolate Mousse with Fresh Fruit Salsa")
Menu.create!(name: "Egg Fried Rice")
Menu.create!(name: "Egg Breakfast Casserole Cc")
Menu.create!(name: "Eggplant with Tomato Tapenade")
Menu.create!(name: "Eggs in Oil with Sumac")
Menu.create!(name: "Eggplant Dip (Baba Ghannooj)")
Menu.create!(name: "Enchiladas Empalmadas (Stacked Enchiladas)")
Menu.create!(name: "Enchiladas Blancas")
Menu.create!(name: "Emerald Isle Cocktail")
Menu.create!(name: "Fabolous Chocolate Cookies")
Menu.create!(name: "Ensuring High-Quality Canned Foods (1/2)")
Menu.create!(name: "Everything But the Kitchen Sink Cookies")
Menu.create!(name: "Farm Journal Beet Relish")
Menu.create!(name: "Fall Lamb and Vegetable Stew")
Menu.create!(name: "Fat-Free Yogurt Cream Sauce")
Menu.create!(name: "Feather Squares")
Menu.create!(name: "Fennel, Sundried and Olive Salad Aug 1997")
Menu.create!(name: "Fettuccini Slaw")
Menu.create!(name: "Filled Hamburgers")
Menu.create!(name: "Fiesta Enchiladas")
Menu.create!(name: "Fiesta Black Beans")
Menu.create!(name: "Fisherman Chowder")
Menu.create!(name: "Fish Sinigang (Sour Soup) in Miso")
Menu.create!(name: "Flake Cheesecake")
Menu.create!(name: "Flip Flop Cake")
Menu.create!(name: "Flounder Florentine")
Menu.create!(name: "Florida Fish")
Menu.create!(name: "Freezer Burritos")
Menu.create!(name: "French Bread Butter")
Menu.create!(name: "Four Barbecue Spice Mixtures (American)")
Menu.create!(name: "French Fried Shoestring Potatoes")
Menu.create!(name: "French Rib Steak with Marrow and Red Wine Sau")
Menu.create!(name: "Fresh Cranberry Sauce")
Menu.create!(name: "Fresh Orange Bread")
Menu.create!(name: "Fresh Strawberry Coffeecake")
Menu.create!(name: "Fresh Strawberry Cake")
Menu.create!(name: "Fried Mashed Plantains")
Menu.create!(name: "Fried Yucca with Feta Cheese Sauce")
Menu.create!(name: "Fried Oysters with Chili Corn Sauce-Brennan's")
Menu.create!(name: "Frosting for Carrot Cake")
Menu.create!(name: "Frozen Pineapple Salad")
Menu.create!(name: "Fruit Cake Preparation")
Menu.create!(name: "Fruit Loaf")
Menu.create!(name: "Fruit-Glazed Roasted Pork-Chops")
Menu.create!(name: "Fruit N Cream Supreme")
Menu.create!(name: "Garden Pasta Sauce (Vegan)")
Menu.create!(name: "Garden Salad")
Menu.create!(name: "Gak Recipe")
Menu.create!(name: "Garlic Mackerel")
Menu.create!(name: "Garlic Soup")
Menu.create!(name: "Garlic New Potato Salad")
Menu.create!(name: "German Potato Salad #3")
Menu.create!(name: "German Short Ribs")
Menu.create!(name: "Gemelli with Ricotta and Spinach")
Menu.create!(name: "Giant Rasin Bran Cookies")
Menu.create!(name: "Giant Oatmeal-Spice Cookies")
Menu.create!(name: "Ginger Glazed Pork Chops")
Menu.create!(name: "Glossary of Ingredients Of Mexican Cooking (3/7)")
Menu.create!(name: "Gloucester Cheese Stew")
Menu.create!(name: "Glynne's Lemon Meringue Pie")
Menu.create!(name: "Golden Apple Chicken Bake")
Menu.create!(name: "Golden Waffles")
Menu.create!(name: "Gnocchi with Mushroom, Tomato and Herb Ragout")
Menu.create!(name: "Gourmet Beef Tenderloins")
Menu.create!(name: "Grand Marnier Sauce")
Menu.create!(name: "Grandmother's Apple Bake")
Menu.create!(name: "Great Antipasto")
Menu.create!(name: "Greek Lamb Burgers")
Menu.create!(name: "Grapefruit Cups Cassis W/borage Flowers")
Menu.create!(name: "Green Beans with Olives")
Menu.create!(name: "Green Corn Pudding")
Menu.create!(name: "Greek-Style Cheesecake")
Menu.create!(name: "Green Tomato Dill Pickles")
Menu.create!(name: "Green Tomatoes with Sour Cream and Havarti")
Menu.create!(name: "Green Rice Casserole #2")
Menu.create!(name: "Grilled Paella")
Menu.create!(name: "Grilled Goat")
Menu.create!(name: "Grilled Haole-Style Yams with Pineapple Butter")
Menu.create!(name: "Grilled Steak")
Menu.create!(name: "Grilled Tofu and Vegetable Brochettes")
Menu.create!(name: "Grilling Ideas (Aicr)")
Menu.create!(name: "Gyuniku No Negimaki (Scallion-Stuffed Beef Rolls)")
Menu.create!(name: "Haleem (Lamb Cooked with Wheat Grains)")
Menu.create!(name: "Habanero Salsa for Canning")
Menu.create!(name: "Hamburger Pasties")
Menu.create!(name: "Ham/triple Pear Puree")
Menu.create!(name: "Ham Rolls")
Menu.create!(name: "Harvey's Sawmill Gravy")
Menu.create!(name: "Hannah's Kitchen Pesto Chicken Pasta Salad")
Menu.create!(name: "Hawaiian Tempeh Kebobs (Vegan)")
Menu.create!(name: "Heavenly Chocolate Cake")
Menu.create!(name: "Hearty Apple Rye Bread")
Menu.create!(name: "Healthy Lemon Bars")
Menu.create!(name: "Hemingway's Trout")
Menu.create!(name: "Herb Garden Leg of Lamb")
Menu.create!(name: "Herb-Grilled Pizza with Prosciutto")
Menu.create!(name: "Holiday Fruitcake")
Menu.create!(name: "Herman Wheat'n'honey Starter")
Menu.create!(name: "Hidden Valley Ranch Style Fajitas")
Menu.create!(name: "Hollandaise")
Menu.create!(name: "Holy Guacamole!")
Menu.create!(name: "Holiday Pumpkin Pie")
Menu.create!(name: "Honey Cinnamon Fruit Dip")
Menu.create!(name: "Honey Baked Chicken Wings")
Menu.create!(name: "Honey Apple Waffles")
Menu.create!(name: "Honey-Grilled Tenderloins")
Menu.create!(name: "Honey Tarts")
Menu.create!(name: "Horseradish/cranberry Dip for Thanksgiving")
Menu.create!(name: "Hot and Sour Stir-Fried Vegetables (Pad Pak Priew Waan)")
Menu.create!(name: "Hot Garlic Wings")
Menu.create!(name: "Hot Cheese and Sausage Dip")
Menu.create!(name: "Hot Slaw")
Menu.create!(name: "How To Bake a Cake (With the Help of A Toddler)")
Menu.create!(name: "Houska (Bohemian Sweet Bread)")
Menu.create!(name: "Impossible Bacon Breakfast Pie (Quiche)")
Menu.create!(name: "Hungarian Soup with Beef Stew")
Menu.create!(name: "Iced Tea (Inst W/lemon An")
Menu.create!(name: "Info - Winter Squash")
Menu.create!(name: "Indo- Carib Grilled Chicken")
Menu.create!(name: "Indian-Style Stuffed Baked Potatoes")
Menu.create!(name: "Island Grilled Bananas")
Menu.create!(name: "Insalata Di Pomodori Del Sud")
Menu.create!(name: "Irish Coffee Muffins")
Menu.create!(name: "Italian Turkey Sausage")
Menu.create!(name: "Jack Daniel's Tennessee Whiskey Chicken")
Menu.create!(name: "Italian Garden Saute")
Menu.create!(name: "Jalapeno Bread (B Crocker)")
Menu.create!(name: "Jamaican Fruit Lamb Chops")
Menu.create!(name: "Jalapeno-Stuffed Steaks")
Menu.create!(name: "Jmeyer Hungarian Gypy Bacon (Ciganyszalonna) or (Zigeunersp")
Menu.create!(name: "Jessica's Favorite Muffins")
Menu.create!(name: "Joey's Seared Collards")
Menu.create!(name: "Justin Wilson's Pot Roast Magnifique")
Menu.create!(name: "Kadju (Curried Cashewnuts)")
Menu.create!(name: "Julian's Cheese Manicotti")
Menu.create!(name: "Kasha Cabbage Rolls")
Menu.create!(name: "Kasha and Mushrooms")
Menu.create!(name: "Kaye's Spinach Madeline")
Menu.create!(name: "Kit's Chocolate Mousse")
Menu.create!(name: "Kiwi Cake")
Menu.create!(name: "King Arthur Flour - Sourdough Starter Tips 1")
Menu.create!(name: "Kohl's Quick Hot 'n Sweet Sauce")
Menu.create!(name: "Kreung Gaeng Masaman (Muslim Curry Paste)")
Menu.create!(name: "Kosher Dills")
Menu.create!(name: "Laura's Pot Roast")
Menu.create!(name: "Latkes")
Menu.create!(name: "Lamb Shanks with Lentils")
Menu.create!(name: "Lebanese Rice and Lentils with Caramelized Onions")
Menu.create!(name: "Leanne Ely's Tuna Casserole in 10 Minutes")
Menu.create!(name: "Layered Lemon Dessert #1")
Menu.create!(name: "Lemon Lush")
Menu.create!(name: "Lemon Loaves")
Menu.create!(name: "Lemon Bisque")
Menu.create!(name: "Lemon-Dill Fish Fillets")
Menu.create!(name: "Lemon Sponge Cups")
Menu.create!(name: "Lemon-Garlic Chicken")
Menu.create!(name: "Lentil Fritters on a Bed of Wilted Beet Greens Vinaigrette")
Menu.create!(name: "Light and Luscious Orange Bars")
Menu.create!(name: "Lettuce Wedge Salad")
Menu.create!(name: "Linguine with Clam Sauce Primavera")
Menu.create!(name: "Linguine Al Limone")
Menu.create!(name: "Linguine in Mushroom Caesar Salad")
Menu.create!(name: "Los Hombres Table Salsa")
Menu.create!(name: "Louisiana Style Bbq Sauce")
Menu.create!(name: "Louisianna Shrimp Salad")
Menu.create!(name: "Low Sugar Pumpkin Torte")
Menu.create!(name: "Low-Fat Fettuccine Alfredo")
Menu.create!(name: "Low-Fat Sub for Buttermilk")
Menu.create!(name: "Maine Sardine Christmas Pate")
Menu.create!(name: "Macaroni with Danish Butter Sauce")
Menu.create!(name: "Make Mine Chocolate Cake")
Menu.create!(name: "Mandarin Soup")
Menu.create!(name: "Making Herb Vinegars 1")
Menu.create!(name: "Mandarin Orange Poke Cake")
Menu.create!(name: "Maple Chiffon Pie")
Menu.create!(name: "Maple Syrup Tart")
Menu.create!(name: "Margaritas #1")
Menu.create!(name: "Marshmallow Crispies")
Menu.create!(name: "Marinated Barbecued Pork Chops")
Menu.create!(name: "Martha's Company Casserole")
Menu.create!(name: "Matthew Kenny's Middle Eastern Salsa Verde")
Menu.create!(name: "Mary Frann's Shrimp in Mayonnaise")
Menu.create!(name: "Masala Sambar")
Menu.create!(name: "Melon Bubbles")
Menu.create!(name: "Meatless Sunday Roast")
Menu.create!(name: "Meat Loaf")
Menu.create!(name: "Mesquite Tortilla Chips")
Menu.create!(name: "Melting Moments #2")
Menu.create!(name: "Meringues (Plain and Chocolate Filled)")
Menu.create!(name: "Microwave Magic Fudge")
Menu.create!(name: "Microwave Kumquat Jam")
Menu.create!(name: "Mexican Make-Ahead Casserole")
Menu.create!(name: "Mincemeat Spice Cake with Egg Nog Topping")
Menu.create!(name: "Mini-Focaccia Rounds")
Menu.create!(name: "Millet Loaf")
Menu.create!(name: "Mocha Blanca Cheesecake")
Menu.create!(name: "Minty Malted Coco Mix")
Menu.create!(name: "Mocha Cookies")
Menu.create!(name: "Mole Pozole")
Menu.create!(name: "Modified Buffalo Wings")
Menu.create!(name: "Mollie's Chicken")
Menu.create!(name: "Monterey Bean Bake")
Menu.create!(name: "Montmorency Cake")
Menu.create!(name: "Moro Rice")
Menu.create!(name: "Mos' Nilly Guacamole")
Menu.create!(name: "Mr Food's Cookies and Cream- 10/31/95")
Menu.create!(name: "Mr Food's Chicken Kiev Roll-Ups")
Menu.create!(name: "Mulling Spice Mix")
Menu.create!(name: "Mushrooms in Chile Sauce")
Menu.create!(name: "Muscadine Habanero Jam")
Menu.create!(name: "My Grandmother's Gefilte Fish Pt 2")
Menu.create!(name: "Nagel Family Crockpot Porkchops")
Menu.create!(name: "My Scones")
Menu.create!(name: "New England Doughnuts")
Menu.create!(name: "Nam Prik for Raw Vegetables (Thai Spice)")
Menu.create!(name: "Nana's Cure-All Banana Loaf")
Menu.create!(name: "Ning Meng Chi P'ien (Fried Chicken Slices with Sour Sauce)")
Menu.create!(name: "Nikki's Eggplant Parmesan")
Menu.create!(name: "New-Loaf: Super Potato Bread")
Menu.create!(name: "Not-So-Sinful Brownies")
Menu.create!(name: "Northern-Style Picodillo")
Menu.create!(name: "Nov-Dinner: Maple Orange Cornish Hens")
Menu.create!(name: "Nutmeg Logs #1")
Menu.create!(name: "Oatmeal with Dates")
Menu.create!(name: "Nutty Cheese Brulee")
Menu.create!(name: "Old Fashioned Dutch Potato Salad - Pennsylvania Dutch")
Menu.create!(name: "Old-Fashioned Hash")
Menu.create!(name: "Old-Fashioned Peach Pie")
Menu.create!(name: "Onion and Parsley Dinner Rolls")
Menu.create!(name: "One-Dish Pork Chop Dinner")
Menu.create!(name: "Onion and Tomato Raita")
Menu.create!(name: "Orange Ginger Fizz")
Menu.create!(name: "Orange Glazed Fresh Baked Ham")
Menu.create!(name: "Orange Chiffon in Raspberry Sauce")
Menu.create!(name: "Oriental Drumsticks")
Menu.create!(name: "Orecchiette with Red Wine Veal Sauce")
Menu.create!(name: "Oriental Openers")
Menu.create!(name: "Ostiones En Escabeche (Soused Oysters)")
Menu.create!(name: "Oriental Vegetable Salad")
Menu.create!(name: "Orzo and Smoked Turkey Salad")
Menu.create!(name: "Oyster Cracker Snack Mix")
Menu.create!(name: "Palatschinken")
Menu.create!(name: "Oyster Sauce Chicken (Ho Yow Gei)")
Menu.create!(name: "Pancit Bijon Guisado")
Menu.create!(name: "Panama Canal Cake")
Menu.create!(name: "Parboiled Noodles with Simmered Chicken")
Menu.create!(name: "Parmesan-Herb Almonds")
Menu.create!(name: "Party Pizzas")
Menu.create!(name: "Parmesan Potato Crisp")
Menu.create!(name: "Pasta Raphael")
Menu.create!(name: "Pasta with Ricotta-Walnut Sauce")
Menu.create!(name: "Pasta Con Sarde")
Menu.create!(name: "Peach Mustard Glazed Pork Chops")
Menu.create!(name: "Peach Crunch (Peach Pie F")
Menu.create!(name: "Peach Walnut Spice Cake")
Menu.create!(name: "Peanut Butter Chip Orange Bar/basic Cookie Mi")
Menu.create!(name: "Peaches and Cream Liqueur")
Menu.create!(name: "Peachy Keen Coffeecake")
Menu.create!(name: "Peanut Sauce (Nuoc Leo)")
Menu.create!(name: "Pear Relish")
Menu.create!(name: "Peas Pudding")
Menu.create!(name: "Pepper Beef Kabobs")
Menu.create!(name: "Penne and Broccoli Salad")
Menu.create!(name: "Pepper Dressing")
Menu.create!(name: "Peppermint Angel Food Cake")
Menu.create!(name: "Peppermint Pinwheels")
Menu.create!(name: "Persimmon Pudding #3")
Menu.create!(name: "Picadillo De Pescado a la Cubana (Cuban Smapper Fish)")
Menu.create!(name: "Pheasant with Roasted Garlic and Lemon")
Menu.create!(name: "Pickled Pumpkin")
Menu.create!(name: "Pickling Basics")
Menu.create!(name: "Pie Dough")
Menu.create!(name: "Pineapple Fried Rice")
Menu.create!(name: "Pinoccate (Pine Nut and Almond Paste Cookies)")
Menu.create!(name: "Pistachio Cake with White Chocolate Buttercream")
Menu.create!(name: "Pistachio Chocolate Apples")
Menu.create!(name: "Plum-Sauced Chicken")
Menu.create!(name: "Pizza on the Grill Pt 2")
Menu.create!(name: "Pizza Dough #09")
Menu.create!(name: "Poires Au Vin Rouge (Pears Poached in Red Wine)")
Menu.create!(name: "Polpette (Meatballs)")
Menu.create!(name: "Polish Sausage and Macaroni")
Menu.create!(name: "Pork (Nz)")
Menu.create!(name: "Pork Chop-Rice Casserole")
Menu.create!(name: "Pork Chops with Stuffing")
Menu.create!(name: "Potato - Dill Soup")
Menu.create!(name: "Portuguese Almond and Potato Cake")
Menu.create!(name: "Portuguese Red Pork")
Menu.create!(name: "Potato Kisses")
Menu.create!(name: "Potato-Corn Chowder")
Menu.create!(name: "Potato and Cucumber Soup-Gurken Und Kartoffelsuppe")
Menu.create!(name: "Potatoes Stuffed with Cheddar Cheese and Bacon")
Menu.create!(name: "Pouissant Au Champagne")
Menu.create!(name: "Prawns with Chimichurri Sauce")
Menu.create!(name: "Provencal Herbed Biscuits")
Menu.create!(name: "Pritiken Fruit Loaf")
Menu.create!(name: "Puffy Omelet Squares")
Menu.create!(name: "Pumpkin Cookies #1")
Menu.create!(name: "Pumpkin Cookies 2")
Menu.create!(name: "Pureed Dates")
Menu.create!(name: "Quick Beef Casserole")
Menu.create!(name: "Quaglie Al Forno")
Menu.create!(name: "Quick Chicken Pasta Salad")
Menu.create!(name: "Quick Potato Pancakes")
Menu.create!(name: "Quick Rye-Batter Buns")
Menu.create!(name: "Quick Little Rib Sauce")
Menu.create!(name: "Rainbow Trout with Spicy Plum Sauce")
Menu.create!(name: "Raspberry Cider")
Menu.create!(name: "Ragged Pasta with a Thousand Herbs")
Menu.create!(name: "Raspberry Vinegar 3")
Menu.create!(name: "Recipie for Leftover Ham")
Menu.create!(name: "Raspberry Yogurt Cake")
Menu.create!(name: "Red Chili Jelly")
Menu.create!(name: "Red Soaked Fresh Fruit Cake")
Menu.create!(name: "Red Sage Quinoa Bread (Abm)")
Menu.create!(name: "Refrigerated Orange Cheesecake")
Menu.create!(name: "Review of Country Life Brunch (Boston)")
Menu.create!(name: "Rhett Butler's Biscuits")
Menu.create!(name: "Rice Bread")
Menu.create!(name: "Rice Pilaf #3")
Menu.create!(name: "Rice and Oyster Dressing")
Menu.create!(name: "Roast Chicken with Spiced Mushroom and Winter Vegetable S")
Menu.create!(name: "Rizogalo")
Menu.create!(name: "Ritzy Macaroni and Cheese")
Menu.create!(name: "Roasted Corn and Bacon Relish")
Menu.create!(name: "Roasted Duckling W/apple Cornbread Dressing, Turned Red Blis")
Menu.create!(name: "Roast Veal with Herbs")
Menu.create!(name: "Roasted Racks of Lamb with Artichokes, Red Onions, and Garli")
Menu.create!(name: "Rooby's Cream of Broccoli Soup")
Menu.create!(name: "Rob's Chili")
Menu.create!(name: "Rose Petal Ice")
Menu.create!(name: "Roswitha's Burning Fruit Salsa")
Menu.create!(name: "Rosemary Lyonnaise Potatoes")
Menu.create!(name: "Rumtopf (Fruit in Rum)")
Menu.create!(name: "Sack Lunch, Chicken")
Menu.create!(name: "Russian Beef Stroganoff")
Menu.create!(name: "Salade Petit Cafe")
Menu.create!(name: "Salsa De Tomatillos Y Chipotles")
Menu.create!(name: "Salmon Patties (Baked)")
Menu.create!(name: "Sangriento Maria")
Menu.create!(name: "Salsify or Vegetable Oyster Soup")
Menu.create!(name: "Salted Cod")
Menu.create!(name: "Sashimi (Sliced Raw Fish) #55")
Menu.create!(name: "Saucy Burgers")
Menu.create!(name: "Sausage Polenta")
Menu.create!(name: "Savory Bruschetta")
Menu.create!(name: "Saute Chicken Breasts")
Menu.create!(name: "Sauteed Beets, Apples and Onions")
Menu.create!(name: "Scallop and Smoked Salmon Pasta")
Menu.create!(name: "Savoy Cabbage and Corn Chowder")
Menu.create!(name: "Scallop and Thyme Ravioli")
Menu.create!(name: "Seafood Boil")
Menu.create!(name: "Scrambled Eggs with Zucchini")
Menu.create!(name: "Seafood Stuffed Pork Tenderloin with Shrimp S")
Menu.create!(name: "Shanghai Tofu Burgers with Chinese Slaw")
Menu.create!(name: "Shake and Bake Mix")
Menu.create!(name: "Shari's Corn Casserole")
Menu.create!(name: "Sherried Kidneys on Toast")
Menu.create!(name: "Shiu My")
Menu.create!(name: "Shortcut Chicken Gravy")
Menu.create!(name: "Shrimp Remoulade Salad")
Menu.create!(name: "Shrimp Creole - New Orleans")
Menu.create!(name: "Shrimp Etouffee #2")
Menu.create!(name: "Shrimp, White Beans, and Tarragon")
Menu.create!(name: "Sinless Sour Cream Cheesecake")
Menu.create!(name: "Simplest Nachos (Vegan)")
Menu.create!(name: "Skewered Fish with Honey-Mustard Sauce")
Menu.create!(name: "Six-Layer Cookie Bar")
Menu.create!(name: "Slow Roasted Onions with Lavender and Thyme")
Menu.create!(name: "Snappy Potato Salad")
Menu.create!(name: "Smoked Turkey-And-Watercress Pitas with Brown Mustard Sauce")
Menu.create!(name: "Smoked Salmon Tartare #2")
Menu.create!(name: "Soaked Boiled Crawfish")
Menu.create!(name: "Snowman Oatmeal Cookies")
Menu.create!(name: "Sorghum Tea Cookies (Corrected)")
Menu.create!(name: "Soured Cream Clam Dip")
Menu.create!(name: "Sour Dough Starter for Breadmaker")
Menu.create!(name: "Sour Curry Paste (Nam Prik Kaeng Som)")
Menu.create!(name: "Southwestern Vegetable Soup")
Menu.create!(name: "Southwestern Seasoning")
Menu.create!(name: "Southwest Potato Topping")
Menu.create!(name: "Spanish Turkey Sausage")
Menu.create!(name: "Spatzle (German Dumplings)")
Menu.create!(name: "Sparerib, Rice and Chick-Pea Casserole")
Menu.create!(name: "Speedy Poached Flounder")
Menu.create!(name: "Spiced Bagna Caoda;fennel, Peppers, Celery Root, Fried Anch")
Menu.create!(name: "Spicy 3 Cheese Macaroni and Cheese")
Menu.create!(name: "Spicy Cream Cheese Pastry")
Menu.create!(name: "Spicy Corn and Tomato Salad")
Menu.create!(name: "Spicy Black Beans with Tomatoes, Onions, and Cilantro")
Menu.create!(name: "Spicy Pineapple Marinade for Chicken")
Menu.create!(name: "Spicy Vinaigrette Dressing")
Menu.create!(name: "Spicy Pear Relish")
Menu.create!(name: "Spinach Dip in Cabbage")
Menu.create!(name: "Spinach Gratin")
Menu.create!(name: "Spirited Black-Eyed Peas")
Menu.create!(name: "Sri Lanka Love Cake Cashew and Pumpkin")
Menu.create!(name: "Steak Dianne")
Menu.create!(name: "Sri Lanka Cutlis Deep Fried Meatballs")
Menu.create!(name: "Steve's Salsa Recipe")
Menu.create!(name: "Steve's Pizza Dough W/secret Ingredient")
Menu.create!(name: "Steamed Fresh Noodles")
Menu.create!(name: "Stir Fried Rice Noodles with Tofu and Egg (Pad Thai)")
Menu.create!(name: "Stir-Fried Rice Noodles W/tofu and Egg (Pa")
Menu.create!(name: "Stir-Fried Shrimp and Chinese Mushrooms")
Menu.create!(name: "Strawberry Yogurt Shake")
Menu.create!(name: "Strawberry Surprise Muffins")
Menu.create!(name: "Strawberry Muffins")
Menu.create!(name: "Streusel Cream Cheese Cake")
Menu.create!(name: "Stuffed Idaho Potatoes")
Menu.create!(name: "Strawberry-Cheese Salad Robert")
Menu.create!(name: "Summer Delight Peach Pie")
Menu.create!(name: "Summer Curried Pea Soup")
Menu.create!(name: "Summer Fruit Chutney")
Menu.create!(name: "Sun Dried Tomato Pesto")
Menu.create!(name: "Sundried Tomato and Olive Quick Bread")
Menu.create!(name: "Super Bowl Dumplings")
Menu.create!(name: "Sweet and Sour Spareribs #1")
Menu.create!(name: "Sweet and Sour Turkey Tenderloins")
Menu.create!(name: "Sweet and Sour Onion Relish")
Menu.create!(name: "Sweet Potatoes and Spinach in Spiced Orange Sauce")
Menu.create!(name: "Sweet Salad Mix")
Menu.create!(name: "Sweet Potato, Cornbread and Sausage Stuffing")
Menu.create!(name: "Szechuan Shredded Beef")
Menu.create!(name: "Szechuan Stir-Fry")
Menu.create!(name: "Sweet-And-Sour Fish")
Menu.create!(name: "Tangy Grilled Chicken")
Menu.create!(name: "Tamale Pie 2")
Menu.create!(name: "Tangy Lemon Chicken Salad")
Menu.create!(name: "Teriyaki Flank Steak")
Menu.create!(name: "Tarte Tatin #1")
Menu.create!(name: "Tarte Tatin (A 'reversed' Apple Pie)")
Menu.create!(name: "Texas Venison Chili")
Menu.create!(name: "Texas Tuna Burgers-Ww")
Menu.create!(name: "Tex-Mex Bean Soup")
Menu.create!(name: "Thanksgiving Menu")
Menu.create!(name: "Three Corn Casserole")
Menu.create!(name: "The Greatest Glazed Nuts")
Menu.create!(name: "Thyme Tea")
Menu.create!(name: "Thyme-Marinated Grilled Asparagus")
Menu.create!(name: "Toffee Popcorn Crunch")
Menu.create!(name: "Tomato Cheddar Soup")
Menu.create!(name: "Tofu Herb Spread")
Menu.create!(name: "Tomato and Onion Sambol")
Menu.create!(name: "Tortillas De Maiz Pt 2")
Menu.create!(name: "Toovar Dal")
Menu.create!(name: "Tomato-Rice Casserole")
Menu.create!(name: "Trofie with Eggplant Pesto")
Menu.create!(name: "Trio of Grains with Sweet Corn Coulis")
Menu.create!(name: "Tropical Cooler")
Menu.create!(name: "Trout Piedmontese Style")
Menu.create!(name: "Turkey and Wildrice Burgers")
Menu.create!(name: "Turkey and Cranberry Chili")
Menu.create!(name: "Turkey Chow Mein Casserole")
Menu.create!(name: "Turkish Chicken with Walnut Sauce")
Menu.create!(name: "Turkey Frame Bean Soup")
Menu.create!(name: "Two-Tone Plum Bowl")
Menu.create!(name: "Uncle Ben's Grilled Stuffed Trout")
Menu.create!(name: "Uff-Da Casserole")
Menu.create!(name: "Valentine Fortunes")
Menu.create!(name: "Vanilla-Bean Custard")
Menu.create!(name: "Vale'rie's Tuna Casserole")
Menu.create!(name: "Vegetable Stuffed Mushrooms")
Menu.create!(name: "Vegetable Stock (Ken Hom)")
Menu.create!(name: "Vegetarian Pasta Sauce")
Menu.create!(name: "Veracruz Salsa (Tomato Chile Salsa)")
Menu.create!(name: "Vermont Maple Cinnamon Swirls")
Menu.create!(name: "Vera's Mince Meat")
Menu.create!(name: "Wan Tan (Wonton)")
Menu.create!(name: "Walnut Coconut Yogurt")
Menu.create!(name: "Vietnamese - Lemongrass Chicken")
Menu.create!(name: "Watkin Wynne Pudding (Welsh)")
Menu.create!(name: "Warm Southwestern Pasta Salad")
Menu.create!(name: "Warm Barley-Vegetable Salad")
Menu.create!(name: "White and Dark Chocolate Dogwood Bark (Marcel Desaulniers)")
Menu.create!(name: "Whipped Jello Filled Angel Food Cake")
Menu.create!(name: "White Chicken Spaghetti")
Menu.create!(name: "White Lasagna")
Menu.create!(name: "White Wine Balls")
Menu.create!(name: "White Chocolate Rasberry Cheesecake")
Menu.create!(name: "Wild Rice- Green Apple Salad")
Menu.create!(name: "Wild Rice-Pine Nut Stuffing")
Menu.create!(name: "Wicklow Pancake")
Menu.create!(name: "Winter Potato Salad with Fresh Fennel")
Menu.create!(name: "With Three")
Menu.create!(name: "Winter Squash Apple and Walnut Soup")
Menu.create!(name: "You Hate Parsnips?")
Menu.create!(name: "Yogurt Deviled Eggs")
Menu.create!(name: "Zabaglione #3")
Menu.create!(name: "Zita Bake Weight Watcher's")
Menu.create!(name: "Zucchini-Apple Pie")
Menu.create!(name: "Zucchini/mushroom Soup")
Menu.create!(name: "Banana Nut Bread")
Menu.create!(name: "Black Eyed Pea and Squash Soup <r T>")
Menu.create!(name: "Apricot Beef Bake")
Menu.create!(name: "Cherry Filling for Pierogies")
Menu.create!(name: "Chanukah Gelt Double Fudge Chocolate Layer Cake")
Menu.create!(name: "Cheesy Egg Bake")
Menu.create!(name: "Easy Apple Kugel")
Menu.create!(name: "Curly Kale and Chick Pea Balti")
Menu.create!(name: "Cuban Black Beans And Rice")
Menu.create!(name: "Herb Focaccia")
Menu.create!(name: "Gourmet Chile Verde")
Menu.create!(name: "Fusilli with Smoked Salmon")
Menu.create!(name: "Kung-Pao Chicken")
Menu.create!(name: "Keftes De Prassa Y Carne (Meat And Leek Patties)")
Menu.create!(name: "Kebab Marinovat (Marinated Lamb Kebab)")
Menu.create!(name: "Louisiana Stuffed Squash")
Menu.create!(name: "Maple Oatmeal Bread")
Menu.create!(name: "Manhattan Clam Chowder, Prince Solms Inn")
Menu.create!(name: "Meat Lasagna")
Menu.create!(name: "Marbled Pumpkin Cheesecake")
Menu.create!(name: "Marnie's Coleslaw Spice Mix")
Menu.create!(name: "Minted Cucumber Salad")
Menu.create!(name: "Mornay Sauce")
Menu.create!(name: "Muesli")
Menu.create!(name: "Nice Cool Salad")
Menu.create!(name: "Oat Bran and Fresh Apple Bread")
Menu.create!(name: "No-Bake Bars")
Menu.create!(name: "Orange-Glazed Carrots and Grapes")
Menu.create!(name: "Pastry Pie Crust (Non-Fat)")
Menu.create!(name: "Pasta and Ceci")
Menu.create!(name: "Penny's Mocha Shake")
Menu.create!(name: "Peach Frozen Yogurt")
Menu.create!(name: "Pecan Loaf")
Menu.create!(name: "Picnic Potatoes")
Menu.create!(name: "Pita Crisps")
Menu.create!(name: "Pork Chops")
Menu.create!(name: "Amerettini And Fresh Fruit Desert")
Menu.create!(name: "All Season Blend")
Menu.create!(name: "Alaskan Cakes")
Menu.create!(name: "Apple Kuchen #2")
Menu.create!(name: "Anne Rosenzweig's Herb Butter")
Menu.create!(name: "Arancine with Sardines And Saffron")
Menu.create!(name: "Avocado Orange Soup")
Menu.create!(name: "Baby Spring Rolls with Ginger Dipping Sauce")
Menu.create!(name: "Baclavas")
Menu.create!(name: "Baked Avocado with Crab")
Menu.create!(name: "Baked Rigatoni with Bolognese Meat Sauce")
Menu.create!(name: "Bacon-Wrapped Trout Stuffed with Balsamic Onion Compote i")
Menu.create!(name: "Basic Brown Onion Sauce")
Menu.create!(name: "Batter Fried Corn-On-The-Cob")
Menu.create!(name: "Banana Rum Rice Fool")
Menu.create!(name: "Bhel with a Difference")
Menu.create!(name: "Bento Boxes with Ellen")
Menu.create!(name: "Bhetki Jhaal Deya")
Menu.create!(name: "Black Russian Cocktail")
Menu.create!(name: "Boogie Brisket")
Menu.create!(name: "Blue Cheese And Walnut Souffles And Mesclun with Red Pepp")
Menu.create!(name: "Brittanys Matzah Brei")
Menu.create!(name: "Breakfast - Corn Griddle Cakes")
Menu.create!(name: "Bow Tie Pasta with Mushrooms, Tomatoes And Artichokes")
Menu.create!(name: "Bucatini All' Amatraciana")
Menu.create!(name: "Caesar's Salad")
Menu.create!(name: "Butterscotch Pudding")
Menu.create!(name: "Candy Cane Platter")
Menu.create!(name: "Carla's Vegetable Loaf")
Menu.create!(name: "Carmelized Endives")
Menu.create!(name: "Celery Root Fries with a Crab Ravigote")
Menu.create!(name: "Celeriac Thins")
Menu.create!(name: "Carrot Soup - Puree")
Menu.create!(name: "Cherry Clafoutis")
Menu.create!(name: "Chicago's 19-Alarm Chili")
Menu.create!(name: "Cheese Baked Enchilada Casserole")
Menu.create!(name: "Chicken Galantine Pt 1")
Menu.create!(name: "Chicken Basilica")
Menu.create!(name: "Chicken Pockets With Goat's Cheese, Poblanos, And Andouil")
Menu.create!(name: "Chicken Tortellini with Red Onion Marmalade")
Menu.create!(name: "Chicken with Lemon Sauce (Cantonese)")
Menu.create!(name: "Chickpea And Root Vegetable Soup")
Menu.create!(name: "Chocolate Dream Torte")
Menu.create!(name: "Choc Hazelnut Mascarpone Torte 1 Pt 2")
Menu.create!(name: "Chocolate Fudge")
Menu.create!(name: "Chocolate Roll with Cappuccino Cream")
Menu.create!(name: "Chocolate Rice Pudding")
Menu.create!(name: "Chunky Tomato Sauce")
Menu.create!(name: "Classic Tuna Sub")
Menu.create!(name: "Cipaille or Cipate (Layered Meat Pie)")
Menu.create!(name: "Cinnamon Apples And Plums")
Menu.create!(name: "Corn Bread with Fresh Tomatoes And Mozzarella")
Menu.create!(name: "Corn Pepian")
Menu.create!(name: "Coriander Chutney (Dhania Ka Chatni)")
Menu.create!(name: "Crab Salad with Hearts of Palm")
Menu.create!(name: "Cranberry Chutney")
Menu.create!(name: "Crab-Stuffed Shrimp with Red Bean Relish")
Menu.create!(name: "Crumpets")
Menu.create!(name: "Creamy Rice Pilaf")
Menu.create!(name: "Creamy Mushroom Chicken")
Menu.create!(name: "Deep Fried Jalapeno Peppers")
Menu.create!(name: "Dhokla (Khaman)")
Menu.create!(name: "Dalmatian Cupcakes")
Menu.create!(name: "Eggplant \"Guacamole\"")
Menu.create!(name: "Easy Burritos")
Menu.create!(name: "Egg Dumplings")
Menu.create!(name: "Faux Bananas Foster")
Menu.create!(name: "Farmhouse Casserole")
Menu.create!(name: "Fiery Hot Habanero Peanuts Ii")
Menu.create!(name: "Four-Fruit Pie")
Menu.create!(name: "Fontina And Tomato Pie (Tortino Di Fontina)")
Menu.create!(name: "Fish Paste")
Menu.create!(name: "Fresh Strawberry Icing")
Menu.create!(name: "Frico Con Patate - (Cheese And Potato Cake)")
Menu.create!(name: "Fruit Salad Sorbet")
Menu.create!(name: "Gelatin Marshmallows")
Menu.create!(name: "Garden Fresh Salsa")
Menu.create!(name: "Ginger Glazed Pear Coffee Cake Ring")
Menu.create!(name: "Gravad Lax ( Tessa )")
Menu.create!(name: "Greek Pita Wrap")
Menu.create!(name: "Golden Crescents")
Menu.create!(name: "Grilled Fish with Cool Bean Salads")
Menu.create!(name: "Grilled Strip Steaks with Olive-Oregano Relish")
Menu.create!(name: "Grilled Chicken Salad with Mangoes And Greens")
Menu.create!(name: "Grilled Tuna W Black Bean Chili, Avocados & Fried Tortillas")
Menu.create!(name: "Grilled Zucchini-White Bean Dip - Ww")
Menu.create!(name: "Hatch Green Chili Salsa")
Menu.create!(name: "Hot And Sour Egg Drop Soup with Quail")
Menu.create!(name: "Herbed Lamb Kebabs with Yogurt Sauce")
Menu.create!(name: "Homemade Herb And Garlic Cheese Spread")
Menu.create!(name: "Jack's Easy Beer Bread")
Menu.create!(name: "Individual Plum Pies with Vanilla Bean Ice Cream")
Menu.create!(name: "Indian Eggs")
Menu.create!(name: "Knuckle of Deer with Wine, Garlic And Rosemary")
Menu.create!(name: "Jasper's Pan-Roasted Lobster with Chervil And Chives")
Menu.create!(name: "Khandvi")
Menu.create!(name: "Lemon And Coriander Pan Fried Trout")
Menu.create!(name: "Le \"Femminelle\" - She-Crabs Marinara")
Menu.create!(name: "Lemon Mop")
Menu.create!(name: "London Broil with Green Peppercorn Butter")
Menu.create!(name: "Light Bites At the Drive-Thru's")
Menu.create!(name: "Low-Fat Pumpkin Cheesecake Pie Pt 2")
Menu.create!(name: "Malloreddus with Creamy Porcini Sauce")
Menu.create!(name: "Marinated Olives with Orange, Fennel And Garlic")
Menu.create!(name: "Marinated Butterfly Lamb with Roast New Potatoes")
Menu.create!(name: "Mike Douglas' Chicken Parmigiana")
Menu.create!(name: "Melting Heart of English Summer Berries with a Crisp Sable")
Menu.create!(name: "Milk Toasted Sandwiches")
Menu.create!(name: "Minted Radish Tea Sandwiches with Lemon Mayonnaise")
Menu.create!(name: "Moroccan Harira Soup")
Menu.create!(name: "Mint Chocolate Chip Ice-Milk Sandwiches")
Menu.create!(name: "Nectarine Mousse Encased in a Brandy Snap Basket")
Menu.create!(name: "New Orleans Bread Bowl")
Menu.create!(name: "Nana's Capsicum Relish")
Menu.create!(name: "Norwegian Lobster with Potato And Sour Cream Salad")
Menu.create!(name: "Oat Coated Carrots")
Menu.create!(name: "Old-Fashioned Cooked Salad Dressing")
Menu.create!(name: "Pan-Roasted Almonds")
Menu.create!(name: "Oyster Wraps with Caviar")
Menu.create!(name: "Oranges in Cinnamon And Grand Marnier")
Menu.create!(name: "Pasta Ai Quattro Formaggio")
Menu.create!(name: "Pasta with Uncooked Tomato And Olive Sauce")
Menu.create!(name: "Party Batons")
Menu.create!(name: "Pear And Currant Streusel Rounds")
Menu.create!(name: "Peanut Shortbread with Guinness Ice Cream, Deep Fried Nuts")
Menu.create!(name: "Pecan Chocolate Tart")
Menu.create!(name: "Pineapple Ice-Cream Cake with Coconut Topping")
Menu.create!(name: "Pineapple Cream Cheese Spread")
Menu.create!(name: "Platter of Fresh Fruits with Mint Gratin And Brandy Snap Ba")
Menu.create!(name: "Pork Wellington")
Menu.create!(name: "Polka Dot Cherry Pie")
Menu.create!(name: "Pork Chops With Curried Apple-Onion Sauce")
Menu.create!(name: "Pulled Pork Sandwich")
Menu.create!(name: "Prawns Alla Plancha")
Menu.create!(name: "Pumpkin Spice Muffins : Applesauce And Sweet Spice")
Menu.create!(name: "Red Potato Skewers")
Menu.create!(name: "Rack of Lamb with Cumin And Thyme")
Menu.create!(name: "Radish And Fennel Salad")
Menu.create!(name: "Ricotta Cheesecake with Marinated Fruit")
Menu.create!(name: "Rich Tofu Creme Cheeze")
Menu.create!(name: "Risotto with Artichoke Hearts, Prosciutto, And Red Bell Pep")
Menu.create!(name: "Roasted Garlic Dressing")
Menu.create!(name: "Roasted Eggplant Stuffed with a Portugese Rice Dressing")
Menu.create!(name: "Roast Prime Ribs of Beef with Shiitake Pan Gravy")
Menu.create!(name: "Rocket Salad with Spiced Salmon And a Honey, Lime And Chill")
Menu.create!(name: "Rosemary Lemon Orzo Pilaf")
Menu.create!(name: "Romanian Sweet Pasta")
Menu.create!(name: "Salt Cod And Potato Gratin")
Menu.create!(name: "Sauce Piquant")
Menu.create!(name: "Salt Cod Chowder")
Menu.create!(name: "Seed Cake")
Menu.create!(name: "Scallops Poached in Chamomile Tea")
Menu.create!(name: "Sayur Manis Bayam Dan Jagung Muda")
Menu.create!(name: "Shanghai Spice Mix")
Menu.create!(name: "Shortcut Sausage By Chef Jennifer Derosa")
Menu.create!(name: "Simple Steak Stirfry")
Menu.create!(name: "Smoked Trout Salpicon")
Menu.create!(name: "Smoked Cheese And Olive Pasta")
Menu.create!(name: "Smoked Sturgeon Terrine")
Menu.create!(name: "Sofyani Chicken Biryani")
Menu.create!(name: "Spaghetti Alla Vongole")
Menu.create!(name: "Spaghetti with Pesto")
Menu.create!(name: "Spicy Black Beans with Bell Peppers And Rice")
Menu.create!(name: "Spiced Yogurt Marinade")
Menu.create!(name: "Spicy Corn Fritters")
Menu.create!(name: "Sponge Pudding And Orange Syrup")
Menu.create!(name: "Spinach And Artichoke Risotto")
Menu.create!(name: "Spicy Vegetable Fritters with Turmeric Yoghurt And Indian S")
Menu.create!(name: "Sticky Rice with Mango")
Menu.create!(name: "Striped Bass with Burgundy Butter Sauce")
Menu.create!(name: "Steamed Squash with Ginger And Saffron")
Menu.create!(name: "Sunday Supper Macaroni And Cheese")
Menu.create!(name: "Stuffed Mussels")
Menu.create!(name: "Sweet And Sour Borscht")
Menu.create!(name: "Sweet And Sour Vegetables")
Menu.create!(name: "Sweet Chestnut Puree")
Menu.create!(name: "Sweet Potato Custard (Sort Of)")
Menu.create!(name: "Thai Chicken or Pork Satay")
Menu.create!(name: "Thai Grilled Chicken")
Menu.create!(name: "Texas Corn Casserole")
Menu.create!(name: "Toblerone Mousse Fondues with Meringues And Fruit")
Menu.create!(name: "Tiny Hamburger Cookies")
Menu.create!(name: "Toasted Pita Chips with Black And White Dips")
Menu.create!(name: "Tomato And Olive Sauce")
Menu.create!(name: "Tony's Summer Pasta")
Menu.create!(name: "Tomato Spice Cake")
Menu.create!(name: "Turkey Korma with Fresh Mango")
Menu.create!(name: "Tuscan Tomato And Bread Salad with Roasted Tomato Vinaigrett")
Menu.create!(name: "Tunnel of Love Cake")
Menu.create!(name: "Vegetable Stems Soup")
Menu.create!(name: "Veggie Vitality Cocktail")
Menu.create!(name: "Vegetable Millet")
Menu.create!(name: "Watercress Salad with Currants And Walnuts")
Menu.create!(name: "Watercress And Radish Stuffed Eggs")
Menu.create!(name: "What's Up Doc, It's a Diuretic")
Menu.create!(name: "Wild Rice Salad")
Menu.create!(name: "Wicked Kicking Salsa")
Menu.create!(name: "Win Deed's Chili")