# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# Environment variables (ENV['...']) can be set in the file config/application.yml.
# See http://railsapps.github.io/rails-environment-variables.html
puts 'ROLES'
YAML.load(ENV['ROLES']).each do |role|
  Role.find_or_create_by_name({ :name => role }, :without_protection => true)
  puts 'role: ' << role
end
puts 'DEFAULT USERS'
user = User.find_or_create_by_email :name => ENV['ADMIN_NAME'].dup, :email => ENV['ADMIN_EMAIL'].dup, :password => ENV['ADMIN_PASSWORD'].dup, :password_confirmation => ENV['ADMIN_PASSWORD'].dup
puts 'user: ' << user.name
user.confirm!
user.add_role :admin

Menu.create!(name: "Mexican Make-Ahead Casserole")
Menu.create!(name: "Mexican Manicotti")
Menu.create!(name: "Mexican Margarita Shrimp")
Menu.create!(name: "Mexican Marinated Carrots (Zanahoria En")
Menu.create!(name: "Mexican Matzo Brei")
Menu.create!(name: "Mexican Max")
Menu.create!(name: "Mexican Meat Loaf Roll")
Menu.create!(name: "Mexican Meat Mix")
Menu.create!(name: "Mexican Meatball Soup")
Menu.create!(name: "Mexican Meatballs")
Menu.create!(name: "Mexican Meatloaf")
Menu.create!(name: "Mexican Medley")
Menu.create!(name: "Mexican Medley Salad")
Menu.create!(name: "Mexican Meringue Cookies")
Menu.create!(name: "Mexican Mev with Beans, Peppers and Jicama")
Menu.create!(name: "Mexican Mince")
Menu.create!(name: "Mexican Mint Marigold (Tagetes Lucida)")
Menu.create!(name: "Mexican Mocha")
Menu.create!(name: "Mexican Mocha Pie")
Menu.create!(name: "Mexican Mole-Style Turkey Chili")
Menu.create!(name: "Mexican Nacho Casserole")
Menu.create!(name: "Mexican Nougat Candy")
Menu.create!(name: "Mexican Octopus Salad")
Menu.create!(name: "Mexican Omelet")
Menu.create!(name: "Mexican Omelet with Chicken")
Menu.create!(name: "Mexican Onion Corn Soup")
Menu.create!(name: "Mexican Orange Candy")
Menu.create!(name: "Mexican Orange Drops")
Menu.create!(name: "Mexican Orange Fudge")
Menu.create!(name: "Mexican Orange Roughy Fillets")
Menu.create!(name: "Mexican Orange Salad")
Menu.create!(name: "Mexican Orange-Almond Cake")
Menu.create!(name: "Mexican Oysters")
Menu.create!(name: "Mexican Pan Bread")
Menu.create!(name: "Mexican Pancake Roll-Ups")
Menu.create!(name: "Mexican Papas Sopa")
Menu.create!(name: "Mexican Pasta")
Menu.create!(name: "Mexican Pasta Pie")
Menu.create!(name: "Mexican Pasta Salad")
Menu.create!(name: "Mexican Pasta Salad Dressing")
Menu.create!(name: "Mexican Pasta Skillet Suppper")
Menu.create!(name: "Mexican Patties")
Menu.create!(name: "Mexican Peanuts")
Menu.create!(name: "Mexican Pepper Casserole")
Menu.create!(name: "Mexican Pepper Chicken")
Menu.create!(name: "Mexican Pepper Steak")
Menu.create!(name: "Mexican Pheasant")
Menu.create!(name: "Mexican Pie")
Menu.create!(name: "Mexican Pie or Upside Down Tamale Pie")
Menu.create!(name: "Mexican Pineapple Dessert with Custard Sauce")
Menu.create!(name: "Mexican Pinto Bean Dip")
Menu.create!(name: "Mexican Pinwheels")
Menu.create!(name: "Mexican Pita Chips")
Menu.create!(name: "Mexican Pita Pizzas")
Menu.create!(name: "Mexican Pita Pockets")
Menu.create!(name: "Mexican Pizza")
Menu.create!(name: "Mexican Pizza Dip")
Menu.create!(name: "Mexican Pizza with Chorizo, Monterey Jack Cheese and Sun-Dri")
Menu.create!(name: "Mexican Pizza with Salsa")
Menu.create!(name: "Mexican Poached Eggs")
Menu.create!(name: "Mexican Polvorones")
Menu.create!(name: "Mexican Pork and Bean Soup")
Menu.create!(name: "Mexican Pork Chops and Beans")
Menu.create!(name: "Mexican Pork Roast")
Menu.create!(name: "Mexican Pork Roast Cooked in Beer W/ Green Sa")
Menu.create!(name: "Mexican Pork Steaks")
Menu.create!(name: "Mexican Pork-Garlic Stew with Hominy")
Menu.create!(name: "Mexican Pot Beans/refried Beans")
Menu.create!(name: "Mexican Pot Pie")
Menu.create!(name: "Mexican Pot Roast")
Menu.create!(name: "Mexican Pot Roast 2")
Menu.create!(name: "Mexican Potato Salad")
Menu.create!(name: "Mexican Potato Skins")
Menu.create!(name: "Mexican Potato Topping")
Menu.create!(name: "Mexican Potato Topping for 4 Baked Potatoes")
Menu.create!(name: "Mexican Potstickers")
Menu.create!(name: "Mexican Pralines")
Menu.create!(name: "Mexican Quiche")
Menu.create!(name: "Mexican Quiche 2")
Menu.create!(name: "Mexican Quiche Con Queso")
Menu.create!(name: "Mexican Rabbit")
Menu.create!(name: "Mexican Rarebit")
Menu.create!(name: "Mexican Red Chile and Citrus Marinade (Spieler)")
Menu.create!(name: "Mexican Red Chile Sauce")
Menu.create!(name: "Mexican Red Chili")
Menu.create!(name: "Mexican Red Onion Soup (Vegan)")
Menu.create!(name: "Mexican Red Pepper and Tomato Soup")
Menu.create!(name: "Mexican Red Rice")
Menu.create!(name: "Mexican Red Salad")
Menu.create!(name: "Mexican Refried Beans")
Menu.create!(name: "Mexican Restaurant Rice")
Menu.create!(name: "Mexican Rice")
Menu.create!(name: "Mexican Rice #1")
Menu.create!(name: "Mexican Rice #2")
Menu.create!(name: "Mexican Rice (Arroz Mexicana)")
Menu.create!(name: "Mexican Rice (Arroz Mexicano)")
Menu.create!(name: "Mexican Rice (Tht)")
Menu.create!(name: "Mexican Rice and Bean Casserole")
Menu.create!(name: "Mexican Rice Cakes")
Menu.create!(name: "Mexican Rice Casserole")
Menu.create!(name: "Mexican Rice Fiesta")
Menu.create!(name: "Mexican Rice Mix")
Menu.create!(name: "Mexican Rice Pudding")
Menu.create!(name: "Mexican Rice Pudding (Arroz Con Leche)")
Menu.create!(name: "Mexican Rice Tart")
Menu.create!(name: "Mexican Rice Toh")
Menu.create!(name: "Mexican Rice with Carrot/peas")
Menu.create!(name: "Mexican Rice, Beans and Sausage")
Menu.create!(name: "Mexican Roast Loin of Pork")
Menu.create!(name: "Mexican Roll-Ups")
Menu.create!(name: "Mexican Rub")
Menu.create!(name: "Mexican Rub Mix")
Menu.create!(name: "Mexican Rubs")
Menu.create!(name: "Mexican S.o.s.")
Menu.create!(name: "Mexican Salad")
Menu.create!(name: "Mexican Salad #1")
Menu.create!(name: "Mexican Salad #2")
Menu.create!(name: "Mexican Salad #3")
Menu.create!(name: "Mexican Salad #4")
Menu.create!(name: "Mexican Salad (Layered)")
Menu.create!(name: "Mexican Salad Bowl")
Menu.create!(name: "Mexican Salad with Avocado Dressing")
Menu.create!(name: "Mexican Salsa")
Menu.create!(name: "Mexican Salsa Chicken")
Menu.create!(name: "Mexican Salsa Dip")
Menu.create!(name: "Mexican Salsa Fria")
Menu.create!(name: "Mexican Salsa Salad")
Menu.create!(name: "Mexican Sausage and Macaroni Salad")
Menu.create!(name: "Mexican Sausage Stew")
Menu.create!(name: "Mexican Seafood Stew")
Menu.create!(name: "Mexican Seasoning")
Menu.create!(name: "Mexican Seasoning Mix (For Taco's)")
Menu.create!(name: "Mexican Shepard Pie")
Menu.create!(name: "Mexican Shepherd's Pie")
Menu.create!(name: "Mexican Shortbread")
Menu.create!(name: "Mexican Shredded Pork")
Menu.create!(name: "Mexican Shredded Spiced Beef (Carnitas)")
Menu.create!(name: "Mexican Shrimp Cocktail")
Menu.create!(name: "Mexican Slaw")
Menu.create!(name: "Mexican Smoked Chile Marinade")
Menu.create!(name: "Mexican Snack Squares")
Menu.create!(name: "Mexican Sombrero Pie")
Menu.create!(name: "Mexican Soup")
Menu.create!(name: "Mexican Spaghetti Pie")
Menu.create!(name: "Mexican Spanish Rice")
Menu.create!(name: "Mexican Spice Mix")
Menu.create!(name: "Mexican Spinach")
Menu.create!(name: "Mexican Spinach and Cheese Pie")
Menu.create!(name: "Mexican Spoon Bread")
Menu.create!(name: "Mexican Steak")
Menu.create!(name: "Mexican Stew")
Menu.create!(name: "Mexican Stewed Fish")
Menu.create!(name: "Mexican Stir Fry")
Menu.create!(name: "Mexican Strata with Chiles and Cheese")
Menu.create!(name: "Mexican Stuffed Chicken")
Menu.create!(name: "Mexican Stuffed Mushrooms")
Menu.create!(name: "Mexican Stuffed Pasta Shells")
Menu.create!(name: "Mexican Stuffed Peppers")
Menu.create!(name: "Mexican Stuffed Sausages")
Menu.create!(name: "Mexican Stuffed Shells")
Menu.create!(name: "Mexican Stuffed Tomatoes")
Menu.create!(name: "Mexican Style Bow Ties")
Menu.create!(name: "Mexican Style Chicken Kiev")
Menu.create!(name: "Mexican Style Chorizo")
Menu.create!(name: "Mexican Style Cornbread")
Menu.create!(name: "Mexican Style Hot Sauce")
Menu.create!(name: "Mexican Style Lasagne")
Menu.create!(name: "Mexican Style Pizza")
Menu.create!(name: "Mexican Style Rice #1")
Menu.create!(name: "Mexican Style Rice #2")
Menu.create!(name: "Mexican Style Short Ribs")
Menu.create!(name: "Mexican Style Vermicelli")
Menu.create!(name: "Mexican Summer Casserole")
Menu.create!(name: "Mexican Summer Stew")
Menu.create!(name: "Mexican Sunrise Punch")
Menu.create!(name: "Mexican Sunset Bread")
Menu.create!(name: "Mexican Sweet Bread")
Menu.create!(name: "Mexican Sweet Bread (Pan Dulce)")
Menu.create!(name: "Mexican T Punch")
Menu.create!(name: "Mexican Table Salsa")
Menu.create!(name: "Mexican Taco Salad")
Menu.create!(name: "Mexican Tea Cakes")
Menu.create!(name: "Mexican Tea Punch")
Menu.create!(name: "Mexican Three-Bean Salad")
Menu.create!(name: "Mexican Tomato Sauce")
Menu.create!(name: "Mexican Topping")
Menu.create!(name: "Mexican Tortilla Salad")
Menu.create!(name: "Mexican Tortilla Soup")
Menu.create!(name: "Mexican Tortilla Special")
Menu.create!(name: "Mexican Tortillas")
Menu.create!(name: "Mexican Turkey Soup")
Menu.create!(name: "Mexican Vegetable Part")
Menu.create!(name: "Mexican Vegetable Salad")
Menu.create!(name: "Mexican Vegetable Soup")
Menu.create!(name: "Mexican Vegetable Stew")
Menu.create!(name: "Mexican Vegetarian Casserole")
Menu.create!(name: "Mexican Wedding Cake")
Menu.create!(name: "Mexican Wedding Cakes")
Menu.create!(name: "Mexican Wedding Cakes (Cookies)")
Menu.create!(name: "Mexican Wedding Cookies")
Menu.create!(name: "Mexican Wedding Dessert")
Menu.create!(name: "Mexican Wedding Ring Cookies")
Menu.create!(name: "Mexican Wings")
Menu.create!(name: "Mexican Winter Squash Soup-Martha Stewart Living")
Menu.create!(name: "Mexican Won Ton")
Menu.create!(name: "Mexican Won Tons")
Menu.create!(name: "Mexican Zucchini")
Menu.create!(name: "Mexican Zucchini and Corn Gratin")
Menu.create!(name: "Mexican Zuccini Skillet")
Menu.create!(name: "Mexican-Bean Salad")
Menu.create!(name: "Mexican-Style Bulgur Salad")
Menu.create!(name: "Mexican-Style Chicken")
Menu.create!(name: "Mexican-Style Chicken Dinner")
Menu.create!(name: "Mexican-Style Chili Beef")
Menu.create!(name: "Mexican-Style Creamed Corn")
Menu.create!(name: "Mexican-Style Dressing")
Menu.create!(name: "Mexican-Style Hominy")
Menu.create!(name: "Mexican-Style Hot Chocolate")
Menu.create!(name: "Mexican-Style Manicotti")
Menu.create!(name: "Mexican-Style Meat Loaf")
Menu.create!(name: "Mexican-Style Pie")
Menu.create!(name: "Mexican-Style Pie (Modified)")
Menu.create!(name: "Mexican-Style Pork Stew")
Menu.create!(name: "Mexican-Style Red Beans")
Menu.create!(name: "Mexican-Style Shredded Pork")
Menu.create!(name: "Mexican: Old El Paso Enchiladas Suiza")
Menu.create!(name: "Mexicana Brunch Pie")
Menu.create!(name: "Mexico City Cake")
Menu.create!(name: "Mexico Giesta Casserole")
Menu.create!(name: "Mexitalian Lasagna")
Menu.create!(name: "Meyer Hungarian Parsley Stuffing for Chicken, Turkey or Veal")
Menu.create!(name: "Meyer Hungarian Stuffed Cabbage (Sorma) Or(Toltottkaposzta)")
Menu.create!(name: "Meyer Lemon Curd")
Menu.create!(name: "Meyer Lemon Sherbet")
Menu.create!(name: "Mezgaldi of Onions")
Menu.create!(name: "Mi Patrona (Washington)")
Menu.create!(name: "Mia's Chili Con Queso")
Menu.create!(name: "Mia's Nutty Shortbread")
Menu.create!(name: "Miami Cuban Picadillo")
Menu.create!(name: "Miami Muffins")
Menu.create!(name: "Miami Salsa")
Menu.create!(name: "Miascia -- Mixed Fruit Tart")
Menu.create!(name: "Mice")
Menu.create!(name: "Micha's Brownie / Fudge Recipe")
Menu.create!(name: "Michael Altenberg's Fingerling Potatoes")
Menu.create!(name: "Michael Bauer's Chewy Chocolate Chip Cookies")
Menu.create!(name: "Michael Cordua's Cilantro Dressing")
Menu.create!(name: "Michael Cron's Chili - Seven Ingredients")
Menu.create!(name: "Michael Douglas' Fruit Plate")
Menu.create!(name: "Michael Gelman's Duck")
Menu.create!(name: "Michael Gelman's Mom's Cherry Duck")
Menu.create!(name: "Michael Jordan's Banana Pudding")
Menu.create!(name: "Michael Jordan's Blackened Catfish")
Menu.create!(name: "Michael Jordan's Cajun Spice")
Menu.create!(name: "Michael Jordan's Crab Cakes")
Menu.create!(name: "Michael Jordan's Grilled Portabello Mushrooms")
Menu.create!(name: "Michael Loo's Chicken Kiev")
Menu.create!(name: "Michael Loo's Lobster Stew")
Menu.create!(name: "Michael Loo's New Mexico Carne Adovada")
Menu.create!(name: "Michael Richard's Oven-Fried Potato Latkes")
Menu.create!(name: "Michael Taus' Vietnamese Fruit Spring Rolls with Ginger Choc")
Menu.create!(name: "Michael's Braised Ribs")
Menu.create!(name: "Michael's Caesar Dressing")
Menu.create!(name: "Michael's Fudge Brownies")
Menu.create!(name: "Michael's Mango Chutney")
Menu.create!(name: "Michael's Mean Green Tomatillo Sauce")
Menu.create!(name: "Michael's Mocha Halo Cakes")
Menu.create!(name: "Michael's Paella")
Menu.create!(name: "Michael's Spaghetti Sauce")
Menu.create!(name: "Michaelmas Broth - Potes Gwyl Mihangel")
Menu.create!(name: "Michel Debost's Ratatouille")
Menu.create!(name: "Michel Richard's Pastry Eggs")
Menu.create!(name: "Michel Stroot's Little Round Pound Cakes")
Menu.create!(name: "Michelangelo's Garlic Spaghetti")
Menu.create!(name: "Michele Bernstein's B T Pasta")
Menu.create!(name: "Michele's Cole Slaw")
Menu.create!(name: "Michele's Favorite Tomato Sauce")
Menu.create!(name: "Michele's Foundation Chowder")
Menu.create!(name: "Michele's Holiday Cake")
Menu.create!(name: "Michele's Salsa")
Menu.create!(name: "Michele's Triple C Cookies")
Menu.create!(name: "Michelle Howe's Passover Rhubarb Cobbler")
Menu.create!(name: "Michelle's Favorite Cookies (Mf)")
Menu.create!(name: "Michelle's Favorite Potato Soup")
Menu.create!(name: "Michelles Pot Roast with Onions, Potatoes and Carrots")
Menu.create!(name: "Michigan Baked Oatmeal")
Menu.create!(name: "Michigan Bbq Style")
Menu.create!(name: "Michigan Beef Steak with Chili-Corn Sauce")
Menu.create!(name: "Michigan Chicken")
Menu.create!(name: "Michigan Chili Dog Sauce")
Menu.create!(name: "Michigan Dried Cherry Apple Stuffed Pork Chops")
Menu.create!(name: "Michigan Minestrone Soup")
Menu.create!(name: "Michigan Pasties")
Menu.create!(name: "Michigan Rocks")
Menu.create!(name: "Michiko's Rice and Chicken")
Menu.create!(name: "Mickey Rooney's Blueberry Delight")
Menu.create!(name: "Mickey Rooney's Creamy Fruit Dessert")
Menu.create!(name: "Mickey Rooney's Fruit Dessert")
Menu.create!(name: "Mickey Rooney's Hangman's Breakfast")
Menu.create!(name: "Mickey's Chicken Soup")
Menu.create!(name: "Mickey's Lasagna")
Menu.create!(name: "Mickey's Potato Casserole")
Menu.create!(name: "Mickey's Potato Soup")
Menu.create!(name: "Mickey's Shaker Chicken")
Menu.create!(name: "Mickey's Stuffed Jalapenos")
Menu.create!(name: "Mickey's Toffee Cake")
Menu.create!(name: "Micro Brews Information")
Menu.create!(name: "Micro Fudge")
Menu.create!(name: "Micro Lemon Meringue Pie")
Menu.create!(name: "Micro Mage's Creamy Rice Pudding")
Menu.create!(name: "Micro Peanut Brittle")
Menu.create!(name: "Micro Pumpkin Seeds")
Menu.create!(name: "Micro Veal Marengo")
Menu.create!(name: "Micro Zucchini")
Menu.create!(name: "Micro-Quick Quesadilla")
Menu.create!(name: "Micro-Wave Oven Cherry Mountain Bars")
Menu.create!(name: "Micro-Wave Peanut Brittle")
Menu.create!(name: "Micronesian Chicken")
Menu.create!(name: "Microware 'roasted' Chestnuts")
Menu.create!(name: "Microwave Apple Crisp")
Menu.create!(name: "Microwave Applesauce")
Menu.create!(name: "Microwave Apricot-Strawberry Compote")
Menu.create!(name: "Microwave Artichokes")
Menu.create!(name: "Microwave Basic Meatloaf")
Menu.create!(name: "Microwave Beef and Mushroom Loaf")
Menu.create!(name: "Microwave Beef Stroganoff")
Menu.create!(name: "Microwave Beer Bread")
Menu.create!(name: "Microwave Black Bean Burritos")
Menu.create!(name: "Microwave Bran Muffins")
Menu.create!(name: "Microwave Bread")
Menu.create!(name: "Microwave Brownies")
Menu.create!(name: "Microwave Butterscotch Applesauce Bars")
Menu.create!(name: "Microwave Cajun Roux")
Menu.create!(name: "Microwave Caramel Corn")
Menu.create!(name: "Microwave Caramel Fudge")
Menu.create!(name: "Microwave Carmel Corn")
Menu.create!(name: "Microwave Carmelcorn")
Menu.create!(name: "Microwave Carrot Cake")
Menu.create!(name: "Microwave Casseroled Chicken")
Menu.create!(name: "Microwave Cauliflower Pick-Ups")
Menu.create!(name: "Microwave Char Siu")
Menu.create!(name: "Microwave Cheese Soup with Vegetables")
Menu.create!(name: "Microwave Cheesecake")
Menu.create!(name: "Microwave Cherry Crisp")
Menu.create!(name: "Microwave Cherry Preserves")
Menu.create!(name: "Microwave Chicken")
Menu.create!(name: "Microwave Chicken Casserole")
Menu.create!(name: "Microwave Chicken Jambalaya")
Menu.create!(name: "Microwave Chicken Teriyaki in a Bag")
Menu.create!(name: "Microwave Children's Clay")
Menu.create!(name: "Microwave Chili Stuffed Baked Potatoes")
Menu.create!(name: "Microwave Chinese Chicken")
Menu.create!(name: "Microwave Chocolate Cake")
Menu.create!(name: "Microwave Chocolate Pie")
Menu.create!(name: "Microwave Corn Beef Pie")
Menu.create!(name: "Microwave Corn on the Cob")
Menu.create!(name: "Microwave Cornbread")
Menu.create!(name: "Microwave Cranberry Orange Relish")
Menu.create!(name: "Microwave Cranberry Sauce")
Menu.create!(name: "Microwave Creamy Fudge")
Menu.create!(name: "Microwave Crunchy Caramel Corn")
Menu.create!(name: "Microwave Divinity")
Menu.create!(name: "Microwave Divinity Candy")
Menu.create!(name: "Microwave Dog Cookies")
Menu.create!(name: "Microwave Doggie Biscuits")
Menu.create!(name: "Microwave Doggie Doughnuts")
Menu.create!(name: "Microwave Double Caramel Munchin' Mix")
Menu.create!(name: "Microwave Duluth Beef Stew")
Menu.create!(name: "Microwave Easy Treat for Dogs")
Menu.create!(name: "Microwave Eggnog Fudge")
Menu.create!(name: "Microwave Eggs in Hash Nests")
Menu.create!(name: "Microwave Field Corn")
Menu.create!(name: "Microwave Finger Paint")
Menu.create!(name: "Microwave Fish with Choice of Seasonings")
Menu.create!(name: "Microwave French Toast")
Menu.create!(name: "Microwave Frozen Vegetables")
Menu.create!(name: "Microwave Fruit Jam")
Menu.create!(name: "Microwave Fudge")
Menu.create!(name: "Microwave Fudge #1")
Menu.create!(name: "Microwave Fudge #2")
Menu.create!(name: "Microwave Fudge #3")
Menu.create!(name: "Microwave German Honey Spice Cake")
Menu.create!(name: "Microwave German Potato Salad")
Menu.create!(name: "Microwave Grains")
Menu.create!(name: "Microwave Grape Jelly")
Menu.create!(name: "Microwave Hard Candy")
Menu.create!(name: "Microwave Hints From Microwave-4-2")
Menu.create!(name: "Microwave Hollandaise Sauce")
Menu.create!(name: "Microwave Honey Granola")
Menu.create!(name: "Microwave Hot Air Nfa Popcorn")
Menu.create!(name: "Microwave Hot Chocolate")
Menu.create!(name: "Microwave Hot Fudge Sauce")
Menu.create!(name: "Microwave Italian Stuffed Peppers")
Menu.create!(name: "Microwave Italian-Style Pot Roast")
Menu.create!(name: "Microwave Jam")
Menu.create!(name: "Microwave Kumquat Jam")
Menu.create!(name: "Microwave Lasagna")
Menu.create!(name: "Microwave Lasagne")
Menu.create!(name: "Microwave Lime Custard")
Menu.create!(name: "Microwave Macadamia-Orange Fudge")
Menu.create!(name: "Microwave Macaroni and Cheese")
Menu.create!(name: "Microwave Magic Fudge")
Menu.create!(name: "Microwave Maple Bacon Oven Pancake")
Menu.create!(name: "Microwave Meatloaf")
Menu.create!(name: "Microwave Mixed Rice")
Menu.create!(name: "Microwave Never-Fail Fudge")
Menu.create!(name: "Microwave New England Boiled Dinner")
Menu.create!(name: "Microwave Oatmeal for One")
Menu.create!(name: "Microwave Parmesan Herb Muffins")
Menu.create!(name: "Microwave Peach Butter")
Menu.create!(name: "Microwave Peach Cobbler")
Menu.create!(name: "Microwave Peanut Brittle")
Menu.create!(name: "Microwave Pecan Brittle")
Menu.create!(name: "Microwave Pecan Pie")
Menu.create!(name: "Microwave Pickles")
Menu.create!(name: "Microwave Pineapple Downside - Up Cake")
Menu.create!(name: "Microwave Play Dough")
Menu.create!(name: "Microwave Poached Pears")
Menu.create!(name: "Microwave Polenta")
Menu.create!(name: "Microwave Popcorn Balls")
Menu.create!(name: "Microwave Potato Salad")
Menu.create!(name: "Microwave Pralines")
Menu.create!(name: "Microwave Pumpkin Butter")
Menu.create!(name: "Microwave Pumpkin Coffee Cake")
Menu.create!(name: "Microwave Pumpkin Spice Cake")
Menu.create!(name: "Microwave Red Hot Apple Jelly")
Menu.create!(name: "Microwave Risotto")
Menu.create!(name: "Microwave Roasted Chicken")
Menu.create!(name: "Microwave Roux")
Menu.create!(name: "Microwave Salmon")
Menu.create!(name: "Microwave Salmon Ring")
Menu.create!(name: "Microwave Salmon Steaks")
Menu.create!(name: "Microwave Salmon Stuffed Potatoes")
Menu.create!(name: "Microwave Scampi")
Menu.create!(name: "Microwave Seafood Newburg")
Menu.create!(name: "Microwave Seafood Paella")
Menu.create!(name: "Microwave Shrimp and Sausage Risotto in Clay Cooker")
Menu.create!(name: "Microwave Southern Cheese Spoon Bread")
Menu.create!(name: "Microwave Spaghetti Sauce")
Menu.create!(name: "Microwave Spiced Pork Chops")
Menu.create!(name: "Microwave Spiced Red Cabbage")
Menu.create!(name: "Microwave Strawberry Jam")
Menu.create!(name: "Microwave Stuffed Peppers")
Menu.create!(name: "Microwave Stuffed Shrimp")
Menu.create!(name: "Microwave Sweet and Sour Pork")
Menu.create!(name: "Microwave Swiss Steak")
Menu.create!(name: "Microwave Teriyaki Chicken in Clay Cooker")
Menu.create!(name: "Microwave Tips - Lasagne")
Menu.create!(name: "Microwave Truffles")
Menu.create!(name: "Microwave Vanilla Pudding")
Menu.create!(name: "Microwave Veal Marengo")
Menu.create!(name: "Microwave Vegetable Quiche")
Menu.create!(name: "Microwave Vegetable Steaming Chart")
Menu.create!(name: "Microwave Waffles Divan")
Menu.create!(name: "Microwave Whole Wheat Bread")
Menu.create!(name: "Microwave Whole-Wheat Banana Muffins")
Menu.create!(name: "Microwave Yogurt")
Menu.create!(name: "Microwave-Dried Tomatoes")
Menu.create!(name: "Microwave: Beef-Topped Tostadas")
Menu.create!(name: "Microwave: Caribbean Fish Steaks")
Menu.create!(name: "Microwave: Mexican Fish Tacos")
Menu.create!(name: "Microwave: Old Fashioned Rice Pudding")
Menu.create!(name: "Microwave: Tuna Bulgur Salad")
Menu.create!(name: "Microwave: Vegetable Burritos")
Menu.create!(name: "Microwaved and Barbecued Beef Ribs")
Menu.create!(name: "Microwaved Baked Potatoes with Salsa")
Menu.create!(name: "Microwaved Brownies")
Menu.create!(name: "Microwaved Fish Italian Style")
Menu.create!(name: "Microwaved Garlic Braised Tuna Steaks")
Menu.create!(name: "Microwaved Norwegian Baked Apples")
Menu.create!(name: "Microwaved Shrimp Scampi")
Menu.create!(name: "Microwaved Sole Parmesan")
Menu.create!(name: "Microwaved Spiced Nuts")
Menu.create!(name: "Microwaved Swiss Steak")
Menu.create!(name: "Microwaving Bread Dough")
Menu.create!(name: "Mid East Mint Lamb")
Menu.create!(name: "Mid Eastern Lamb Stew")
Menu.create!(name: "Mid-East Pilaf")
Menu.create!(name: "Mid-East Spinach Salad")
Menu.create!(name: "Midas Touch Bloody Marys")
Menu.create!(name: "Middle East Dip")
Menu.create!(name: "Middle Eastern Bean and Roasted Vegetable Salad (Mf)")
Menu.create!(name: "Middle Eastern Black Bean Salad")
Menu.create!(name: "Middle Eastern Carrot Salad")
Menu.create!(name: "Middle Eastern Chicken with Rice")
Menu.create!(name: "Middle Eastern Delight")
Menu.create!(name: "Middle Eastern Falafel Sandwiches")
Menu.create!(name: "Middle Eastern Flatbread")
Menu.create!(name: "Middle Eastern Fondue")
Menu.create!(name: "Middle Eastern Jerky")
Menu.create!(name: "Middle Eastern Kebabs")
